branches:
  only:
  - main
language: python
python:
  - "3.9"
# Install dependencies
install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: Test with Pytest
      script: python3 -m pytest -v tests/test_dice.py
