name: github-python-actions
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: installing requirements
        uses: py-actions/py-dependency-install@v2      
        with:
          path: "./requirements.txt"
      - name: deploying with heroku -staging
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: knire-ci-me-dice-on-demand
          heroku_email: "daniel.naranjo1999@gmail.com"
      - name: unit test
        run: |
          python3 -m venv venv
          venv/bin/activate
          python3 -m pytest -v tests/test_dice.py
      - name: deploy to prod with heroku
        if: success()
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: knire-ci-me-dice-on-demand-prd
          heroku_email: "daniel.naranjo1999@gmail.com"      
      - name: notify success with slack
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel_id: C02MNT1KCBF
          status: SUCCESS
          color: good
      - name: notify failure with slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel_id: C02MNT1KCBF
          status: FAILED
          color: danger
